"""Tests for the DTS writer (board and overlay modes)."""

from __future__ import annotations

import textwrap
import pytest

from mx2dts.dts_writer import generate_dts
from tests.conftest import make_ioc, make_ctx, MINIMAL_IOC


def _ctx(tmp_path, extra_ioc=""):
    full = MINIMAL_IOC + extra_ioc
    ioc_path = tmp_path / "board.ioc"
    ioc_path.write_text(textwrap.dedent(full))
    from mx2dts.ioc_parser import parse_ioc
    ioc = parse_ioc(ioc_path)
    return make_ctx(ioc, tmp_path)


# ── Board mode ────────────────────────────────────────────────────────────────

def test_board_mode_has_dts_version(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="board")
    assert "/dts-v1/;" in out


def test_board_mode_has_root_node(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="board")
    assert "model =" in out
    assert "compatible =" in out
    assert "zephyr,sram" in out
    assert "zephyr,flash" in out


def test_board_mode_has_console_chosen(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="board")
    assert "zephyr,console" in out


def test_board_mode_has_usart2(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="board")
    assert "&usart2" in out
    assert 'current-speed = <115200>' in out


def test_board_mode_flash_partitions(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="board")
    # STM32L476RGTx has 1MB flash (flash code G)
    assert "flash0" in out
    assert "storage_partition" in out


def test_board_mode_custom_board_name(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, board_name="My Custom Board", mode="board")
    assert "My Custom Board" in out


# ── Overlay mode ──────────────────────────────────────────────────────────────

def test_overlay_mode_no_dts_version(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="overlay")
    assert "/dts-v1/;" not in out


def test_overlay_mode_no_root_node(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="overlay")
    assert 'model = "' not in out
    assert "zephyr,sram" not in out


def test_overlay_mode_no_flash_partitions(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="overlay")
    assert "flash0" not in out
    assert "storage_partition" not in out


def test_overlay_mode_has_peripherals(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="overlay")
    assert "&usart2" in out
    assert 'current-speed = <115200>' in out


def test_overlay_mode_has_header_comment(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx, mode="overlay")
    assert "Auto-generated by mx2dts" in out


def test_default_mode_is_board(tmp_path):
    ctx = _ctx(tmp_path)
    out = generate_dts(ctx)
    assert "/dts-v1/;" in out


# ── Warning rendering ─────────────────────────────────────────────────────────

def test_warnings_appear_in_output(tmp_path):
    ctx = _ctx(tmp_path)
    ctx.warn("test warning message")
    out = generate_dts(ctx, mode="board")
    assert "test warning message" in out
    assert "Conversion warnings" in out


def test_no_warnings_section_when_clean(tmp_path):
    """Warnings section only appears when ctx.warnings is non-empty."""
    from mx2dts.dts_writer import _render_warnings
    from mx2dts.context import ConversionContext
    from unittest.mock import MagicMock

    ctx = MagicMock(spec=ConversionContext)
    ctx.warnings = []
    assert _render_warnings(ctx) == []


# ── DtsNode rendering ─────────────────────────────────────────────────────────

def test_dts_node_render_basic():
    from mx2dts.converters import DtsNode
    node = DtsNode(ref="&usart2", properties={"status": '"okay"', "current-speed": "<115200>"})
    text = node.render()
    assert text.startswith("&usart2 {")
    assert 'status = "okay";' in text
    assert "current-speed = <115200>;" in text
    assert text.strip().endswith("};")


def test_dts_node_render_with_children():
    from mx2dts.converters import DtsNode
    child = DtsNode(ref="led0: led0", properties={"gpios": "<&gpioa 5 GPIO_ACTIVE_HIGH>"})
    parent = DtsNode(ref="leds", properties={"compatible": '"gpio-leds"'}, children=[child])
    text = parent.render()
    assert "leds {" in text
    assert "led0: led0 {" in text
    assert "gpios" in text


def test_dts_node_render_with_comment():
    from mx2dts.converters import DtsNode
    node = DtsNode(ref="&mac", properties={"status": '"okay"'}, comment="Verify PHY settings")
    text = node.render()
    assert "/* Verify PHY settings */" in text
