"""Assemble final Zephyr DTS from conversion context and converter outputs."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .context import ConversionContext
from .converters import ALL_CONVERTERS, DtsNode, DmaConverter
from .ioc_parser import IocFile


_HEADER = """\
/*
 * Auto-generated by mx2dts from {ioc_name}
 * MCU: {mcu_name}
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * WARNING: Review all values before using in production.
 * DMA request numbers and some clock settings may need manual verification.
 */
"""

_DTS_VERSION = "/dts-v1/;"


def generate_dts(
    ctx: ConversionContext,
    board_name: Optional[str] = None,
    mode: str = "board",
) -> str:
    """Run all converters and assemble a .dts or .overlay file string.

    Args:
        ctx:        Conversion context.
        board_name: Optional board model name (board mode only).
        mode:       ``"board"`` (default) for a full DTS file, or
                    ``"overlay"`` for a minimal Zephyr project overlay.
    """
    if mode == "overlay":
        return _generate_overlay(ctx)
    return _generate_board(ctx, board_name)


# ── Board mode ─────────────────────────────────────────────────────────────────

def _generate_board(ctx: ConversionContext, board_name: Optional[str]) -> str:
    lines: list[str] = []

    # Header comment
    lines.append(_HEADER.format(
        ioc_name=ctx.ioc.path.name,
        mcu_name=ctx.ioc.mcu_user_name or ctx.ioc.mcu_name,
    ))
    lines.append(_DTS_VERSION)
    lines.append("")

    # Includes
    soc_include = ctx.soc_dtsi_include
    pinctrl_include = ctx.pinctrl_dtsi_include

    if soc_include:
        lines.append(f"#include <{soc_include}>")
    else:
        ctx.warn("Could not determine SoC DTSI include path")
        lines.append("/* TODO: add SoC DTSI include, e.g.: */")
        lines.append(f"/* #include <st/{ctx.mcu.family_dir or 'FAMILY'}/stm32XXXX.dtsi> */")

    if pinctrl_include:
        lines.append(f"#include <{pinctrl_include}>")
    else:
        ctx.warn("Could not determine pinctrl DTSI include path")
        lines.append("/* TODO: add pinctrl DTSI include */")

    lines.extend(_extra_includes(ctx))
    lines.append("")

    # Run converters
    all_nodes, dma_converter = _run_converters(ctx)

    # Root node
    lines.append(_make_root_node(ctx, board_name))
    lines.append("")

    # Peripheral overlay nodes
    lines.extend(_render_nodes(all_nodes))

    # DMA properties merged into peripheral nodes
    lines.extend(_render_dma_props(dma_converter))

    # Warning summary
    lines.extend(_render_warnings(ctx))

    return "\n".join(lines) + "\n"


# ── Overlay mode ───────────────────────────────────────────────────────────────

def _generate_overlay(ctx: ConversionContext) -> str:
    lines: list[str] = []

    lines.append(_HEADER.format(
        ioc_name=ctx.ioc.path.name,
        mcu_name=ctx.ioc.mcu_user_name or ctx.ioc.mcu_name,
    ))

    lines.extend(_extra_includes(ctx))
    if lines[-1] != "":
        lines.append("")

    # Run converters
    all_nodes, dma_converter = _run_converters(ctx)

    # Peripheral overlay nodes only (no root node, no flash)
    lines.extend(_render_nodes(all_nodes))

    # DMA properties
    lines.extend(_render_dma_props(dma_converter))

    # Warning summary
    lines.extend(_render_warnings(ctx))

    return "\n".join(lines) + "\n"


# ── Shared helpers ─────────────────────────────────────────────────────────────

def _extra_includes(ctx: ConversionContext) -> list[str]:
    """Extra #include lines needed regardless of mode (e.g., input event codes)."""
    result = []
    gpio_pins = ctx.ioc.gpio_pins()
    if any(not p.is_skip and not _is_output_signal(p.signal) for p in gpio_pins):
        result.append("#include <zephyr/dt-bindings/input/input-event-codes.h>")
    return result


def _run_converters(ctx: ConversionContext) -> tuple[list[DtsNode], Optional[DmaConverter]]:
    all_nodes: list[DtsNode] = []
    dma_converter: Optional[DmaConverter] = None
    for converter_cls in ALL_CONVERTERS:
        converter = converter_cls()
        nodes = converter.convert(ctx)
        all_nodes.extend(nodes)
        if isinstance(converter, DmaConverter):
            dma_converter = converter
    return all_nodes, dma_converter


def _render_nodes(nodes: list[DtsNode]) -> list[str]:
    lines = []
    for node in nodes:
        lines.append(node.render())
        lines.append("")
    return lines


def _render_dma_props(dma_converter: Optional[DmaConverter]) -> list[str]:
    if not (dma_converter and dma_converter.peripheral_dma_props):
        return []
    lines = [
        "/*",
        " * DMA assignments — merge into the peripheral nodes above",
        " * and verify channel / request numbers against your MCU's DMA table:",
    ]
    for periph, props in dma_converter.peripheral_dma_props.items():
        lines.append(" *")
        lines.append(f" * &{periph} {{")
        for k, v in props.items():
            lines.append(f" *\t{k} = {v};")
        lines.append(" * };")
    lines += [" */", ""]
    return lines


def _render_warnings(ctx: ConversionContext) -> list[str]:
    if not ctx.warnings:
        return []
    lines = [
        "/*",
        " * ── Conversion warnings ─────────────────────────────────────────",
    ]
    for i, w in enumerate(ctx.warnings, 1):
        lines.append(f" * [{i:02d}] {w}")
    lines.append(" */")
    return lines


def _make_root_node(ctx: ConversionContext, board_name: Optional[str]) -> str:
    ioc = ctx.ioc
    mcu_user = (ioc.mcu_user_name or ioc.mcu_name).replace("(", "").replace(")", "")
    model_name = board_name or f"Custom {mcu_user} board"

    # Derive compatible string: "st,stm32l476rg"
    compat = f"st,{mcu_user.lower().rstrip('x')}"

    # Chosen: always include sram/flash
    chosen: list[str] = [
        '\t\tzephyr,sram = &sram0;',
        '\t\tzephyr,flash = &flash0;',
    ]

    # If USART2 or USART1 is active, suggest console
    for uart in ["usart2", "usart1", "usart3", "lpuart1"]:
        if ioc.has_ip(uart.upper()):
            chosen.append(f'\t\tzephyr,console = &{uart};')
            chosen.append(f'\t\tzephyr,shell-uart = &{uart};')
            break

    chosen_block = "\n".join(chosen)

    # Flash partitions (generic — user should verify sizes)
    mcu_info = ctx.mcu
    flash_kb = _detect_flash_kb(ioc, mcu_info)
    storage_offset, storage_size = _storage_partition(flash_kb)
    flash_block = ""
    if flash_kb:
        flash_block = f"""
&flash0 {{
\tpartitions {{
\t\tcompatible = "fixed-partitions";
\t\t#address-cells = <1>;
\t\t#size-cells = <1>;

\t\t/* {flash_kb}KB flash — adjust storage partition as needed */
\t\tstorage_partition: partition@{storage_offset:x} {{
\t\t\tlabel = "storage";
\t\t\treg = <0x{storage_offset:08x} DT_SIZE_K({storage_size})>;
\t\t}};
\t}};
}};"""

    return f"""\
/ {{
\tmodel = "{model_name}";
\tcompatible = "{compat}";

\tchosen {{
{chosen_block}
\t}};
}};
{flash_block}"""


def _is_output_signal(signal: str) -> bool:
    return signal in ("GPIO_Output",)


def _detect_flash_kb(ioc: IocFile, mcu_info) -> Optional[int]:
    from .mcu_db import FLASH_SIZE_MAP
    # Try user MCU name flash code
    name = ioc.mcu_user_name or ioc.mcu_name
    import re
    m = re.search(r"STM32\w+?([BCDEFGHIJKZ])[A-Z][a-z]", name, re.IGNORECASE)
    if m:
        code = m.group(1).upper()
        if code in FLASH_SIZE_MAP:
            return FLASH_SIZE_MAP[code]
    return None


def _storage_partition(flash_kb: Optional[int]) -> tuple[int, int]:
    """Return (offset_bytes, size_kb) for a generic storage partition at end of flash."""
    if flash_kb is None:
        return (0x0007_8000, 32)
    storage_kb = max(32, flash_kb // 32)
    offset = (flash_kb - storage_kb) * 1024
    return offset, storage_kb
